formatter: markdown table

settings:
  anchor: false
  escape: false
  indent: 4

output:
  file: ../../README.md
  mode: inject
  template: |-
    <!-- S3_CLOUDFRONT -->
    {{ .Content }}
    <!-- S3_CLOUDFRONT -->